// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

// Back-compat shim — the guidance engine now lives in modules/guidance/.
// This re-export exists so legacy imports of './guidance-engine.js' keep working.

export * from './guidance/index.js';
