// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─────────────────────────────────────────────────────────────────────────────
//  Config loader (hot-reloadable)
//  Uses PERSISTENT_DATA_DIR (Render disk) when available, falls back to local data/
//  #51: Config is cached in memory and hot-reloaded on file change via fs.watch
// ─────────────────────────────────────────────────────────────────────────────

const _persistDir = process.env.PERSISTENT_DATA_DIR;
const CONFIG_PATH = _persistDir
  ? path.join(_persistDir, 'guidance-config.json')
  : path.join(__dirname, '../data/guidance-config.json');
const _SEED_PATH = path.join(__dirname, '../data/guidance-config.json');
const DEFAULT_CONFIG = { _info: 'Guidance config', _schema_version: 1, worlds: [] };
let _config = null;
let _configMtime = 0;

export function loadConfig(force = false) {
  if (!force && _config) {
    // Quick mtime check — only re-read if file changed (#51)
    try {
      const stat = fs.statSync(CONFIG_PATH);
      if (stat.mtimeMs <= _configMtime) return _config;
    } catch { /* fall through to full load */ }
  }
  if (!fs.existsSync(CONFIG_PATH)) {
    if (_persistDir && fs.existsSync(_SEED_PATH)) {
      fs.copyFileSync(_SEED_PATH, CONFIG_PATH);
    } else {
      fs.writeFileSync(CONFIG_PATH, JSON.stringify(DEFAULT_CONFIG, null, 2), 'utf8');
    }
  }
  _config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf8'));
  try { _configMtime = fs.statSync(CONFIG_PATH).mtimeMs; } catch { _configMtime = Date.now(); }
  return _config;
}

export function saveConfig(cfg) {
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(cfg, null, 2), 'utf8');
  _config = cfg;
  try { _configMtime = fs.statSync(CONFIG_PATH).mtimeMs; } catch { _configMtime = Date.now(); }
}

export function getConfig() { return loadConfig(); }

// ─────────────────────────────────────────────────────────────────────────────
//  Helper: parse JSON-string values from save data
//  #39: Cache parsed values per evaluation using a WeakMap keyed on `data`
// ─────────────────────────────────────────────────────────────────────────────

const _pkCache = new WeakMap(); // data object → Map<key, parsed>

function _pk(data, key) {
  let v = data[key];
  if (v == null) return null;
  if (typeof v !== 'string') return v; // already parsed (number/array/object)
  // Check cache
  let cache = _pkCache.get(data);
  if (cache) {
    if (cache.has(key)) return cache.get(key);
  } else {
    cache = new Map();
    _pkCache.set(data, cache);
  }
  try {
    const parsed = JSON.parse(v);
    cache.set(key, parsed);
    return parsed;
  } catch {
    cache.set(key, null);
    return null;
  }
}

export { _pk, _pkCache };
