// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

import { loadConfig } from './config.js';
import { EXTRACTORS } from './extractors.js';
import { _extractorLRU, _setLastEvalProfile } from './profile.js';
import { loadCustomExtractors, evaluateCustomExtractor } from './custom-extractors.js';

// ─────────────────────────────────────────────────────────────────────────────
//  Tier evaluation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Given a value and an ascending tiers array, determines the current tier.
 *
 * Tier objects support an optional `type` field (defaults to "gte"):
 *   "gte"         — value >= threshold  (default, backward-compatible)
 *   "unlocked"    — value >= 1  (bool display: ✓/✗)
 *   "count_of_n"  — value >= threshold, displays as "X / total"
 *   "pct"         — value 0–100 treated as %, displays as "X%"
 *   "has_item"    — value is 0|1 from parameterised extractor, bool display
 *   "max_any"     — value >= threshold, displays as "Best: X"
 *   "avg"         — value >= threshold, displays as "avg X"
 *   "per_char"    — value >= threshold (count of qualifying chars)
 *   "compound_and"— all conditions[] must individually pass; ignores `value`
 *   "rate"        — value >= threshold, displays with `per` ("hour"/"day")
 *   "lte"         — value <= threshold  (lower is better, e.g. death count)
 *   "between"     — value in [threshold, max]  (range check)
 *   "eq"          — value === threshold  (exact match)
 *   "not"         — value < threshold    (negation / absence check)
 *
 * Extra tier fields used by specific types:
 *   total     — (count_of_n) denominator shown in display
 *   per       — (rate) unit string, e.g. "hour" or "day"
 *   conditions— (compound_and) [{extractor, threshold}, ...]
 *
 * @param {number}  value  — extracted value (ignored for compound_and)
 * @param {Array}   tiers  — ascending tier config array
 * @param {object}  save   — full save object; only needed for compound_and tiers
 */
// #44: Cache tier threshold sequences (keyed on tiers array reference)
const _tierThresholdCache = new WeakMap();
function _getTierThresholds(tiers) {
  if (_tierThresholdCache.has(tiers)) return _tierThresholdCache.get(tiers);
  const thresholds = tiers.map(t => t.threshold ?? 0);
  _tierThresholdCache.set(tiers, thresholds);
  return thresholds;
}

function evaluateTiers(value, tiers, save = null) {
  if (!Array.isArray(tiers) || tiers.length === 0) {
    return { tierIndex: -1, tierLabel: 'No tiers', currentThreshold: 0, nextTier: null, nextThreshold: null, pct: 0, value, displayType: 'gte', total: null, per: null };
  }

  let tierIndex = -1;
  for (let i = 0; i < tiers.length; i++) {
    const tier = tiers[i];
    const type = tier.type || 'gte';
    let passes = false;

    if (type === 'compound_and') {
      if (save && Array.isArray(tier.conditions) && tier.conditions.length > 0) {
        passes = tier.conditions.every(cond => {
          const fn = EXTRACTORS[cond.extractor];
          if (!fn) return false;
          try { return (fn(save) ?? 0) >= cond.threshold; }
          catch { return false; }
        });
      }
    } else if (type === 'compound_or') {
      // #42: OR logic — any condition met = tier passes
      if (save && Array.isArray(tier.conditions) && tier.conditions.length > 0) {
        passes = tier.conditions.some(cond => {
          const fn = EXTRACTORS[cond.extractor];
          if (!fn) return false;
          try { return (fn(save) ?? 0) >= cond.threshold; }
          catch { return false; }
        });
      }
    } else if (type === 'lte') {
      // Value must be <= threshold (lower is better, e.g. death count, idle time)
      passes = value <= tier.threshold;
    } else if (type === 'between') {
      // Value must be in [threshold, max] range
      passes = value >= tier.threshold && value <= (tier.max ?? Infinity);
    } else if (type === 'eq') {
      // Exact match
      passes = value === tier.threshold;
    } else if (type === 'not') {
      // Negation: passes when value does NOT meet threshold
      passes = value < tier.threshold;
    } else {
      passes = value >= tier.threshold;
    }

    // #60: Tier skip logic — if a higher tier passes, skip lower ones
    if (passes) tierIndex = i;
    else if (type !== 'compound_and' && type !== 'compound_or') break;
    // For compound types, continue checking higher tiers (non-sequential)
  }

  const currentTier   = tierIndex >= 0 ? tiers[tierIndex] : null;
  const nextTier      = tierIndex < tiers.length - 1 ? tiers[tierIndex + 1] : null;
  const nextThreshold = nextTier ? nextTier.threshold : null;

  // Display type is taken from the current tier (or next tier if none reached yet)
  const displayType   = (currentTier || nextTier || tiers[0])?.type || 'gte';

  let pct = 0;
  if (nextThreshold !== null) {
    const base  = currentTier ? currentTier.threshold : 0;
    const range = nextThreshold - base;
    // For non-numeric types, pct progress isn't meaningful — set to 0
    if (displayType === 'compound_and' || displayType === 'compound_or') {
      // Calculate compound progress as fraction of conditions met
      const compoundTier = nextTier || currentTier;
      if (save && compoundTier && Array.isArray(compoundTier.conditions) && compoundTier.conditions.length > 0) {
        let met = 0;
        for (const cond of compoundTier.conditions) {
          const fn = EXTRACTORS[cond.extractor];
          if (fn) { try { if ((fn(save) ?? 0) >= cond.threshold) met++; } catch {} }
        }
        pct = met / compoundTier.conditions.length;
      } else {
        pct = 0;
      }
    } else if (displayType === 'lte') {
      // Inverted progress: lower value = more progress
      pct = range > 0 ? Math.max(0, Math.min(1, (nextThreshold - value) / range)) : 1;
    } else {
      // #56: Smart interpolation — clamp to [0,1] for smooth progress bars
      pct = range > 0 ? Math.max(0, Math.min(1, (value - base) / range)) : 1;
    }
  } else {
    pct = 1; // Already at max tier
  }
  // #44: Use cached thresholds for any threshold-related lookups
  _getTierThresholds(tiers); // warm cache

  return {
    tierIndex,
    tierLabel: currentTier ? currentTier.label : 'None',
    currentThreshold: currentTier ? (currentTier.threshold ?? 0) : 0,
    nextTier: nextTier ? nextTier.label : null,
    nextThreshold,
    nextNote: nextTier ? (nextTier.note || null) : null,
    pct: Math.round(pct * 1000) / 1000,
    atMax: nextTier === null,
    value,
    displayType,
    // Type-specific display hints
    total: currentTier?.total ?? null,
    per: currentTier?.per ?? null,
    // All upcoming tiers (for sub-card display in review UI)
    upcomingTiers: tiers.slice(tierIndex + 1).map(function(t) {
      return { label: t.label, threshold: t.threshold, note: t.note || null, type: t.type || 'gte', total: t.total || null, per: t.per || null, param: t.param ?? null };
    }),
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Card evaluation
// ─────────────────────────────────────────────────────────────────────────────

function evaluateCard(card, save, profile = null) {
  // Info cards are static text — no extraction or scoring needed
  if (card.cardType === 'info') {
    return {
      id: card.id,
      label: card.label,
      icon: card.icon,
      cardType: 'info',
      text: card.text || '',
      weight: 0,
      unit: '',
      extractor: null,
      value: 0,
      error: null,
      tierIndex: -1,
      tierLabel: null,
      currentThreshold: 0,
      nextTier: null,
      nextThreshold: null,
      pct: 0,
      atMax: true,
      displayType: 'info',
      total: null,
      per: null,
      upcomingTiers: [],
      weightedScore: 0,
      maxScore: 0,
      // Display config pass-through
      pinned: !!card.pinned,
      hideIfMaxed: !!card.hideIfMaxed,
      progressStyle: card.progressStyle || 'bar',
      displayFormat: card.displayFormat || 'number',
      showBenchmark: card.showBenchmark !== false,
    };
  }

  const extractor = EXTRACTORS[card.extractor];
  let value = 0;
  let error = null;
  const t0 = profile ? performance.now() : 0;

  if (!extractor) {
    // Fall back to custom extractors
    const customDefs = loadCustomExtractors();
    const customDef = customDefs.find(d => d.id === card.extractor);
    if (customDef) {
      try {
        const paramTier = card.tiers?.find(t => t.param != null);
        const cardParam = card.param ?? paramTier?.param ?? null;
        value = evaluateCustomExtractor(customDef, save, cardParam) ?? 0;
      } catch (e) { error = e.message; }
    } else {
      error = `Unknown extractor: ${card.extractor}`;
    }
  } else {
    // #63: Check LRU cache first
    const paramTier = card.tiers?.find(t => t.param != null);
    const cardParam = card.param ?? paramTier?.param ?? null;
    const cacheKey = card.extractor + (cardParam != null ? ':' + cardParam : '');
    const cached = _extractorLRU.get(cacheKey);
    if (cached !== undefined) {
      value = cached;
    } else {
      try {
        value = cardParam != null
          ? (extractor(save, cardParam) ?? 0)
          : (extractor(save) ?? 0);
        // #53: Return type validation — warn if extractor returns non-number
        if (typeof value !== 'number' || !isFinite(value)) {
          value = Number(value) || 0;
        }
        // #62: avg_per_char mode — divide by character count
        if (card.mode === 'avg_per_char') {
          const chars = save?.CharacterCount ?? save?.playerCount ?? 1;
          value = chars > 0 ? value / chars : value;
        }
        _extractorLRU.set(cacheKey, value);
      } catch (e) { error = e.message; }
    }
  }

  // #40: Record extractor timing
  if (profile) {
    const elapsed = performance.now() - t0;
    profile.push({ extractor: card.extractor, ms: Math.round(elapsed * 100) / 100 });
  }

  // #43: Exclude error cards from scoring — set weight to 0 on error
  // #48: Conditional weights — weight can be { base, conditions: [{ extractor, threshold, weight }] }
  let effectiveWeight;
  if (error) {
    effectiveWeight = 0;
  } else if (card.weight && typeof card.weight === 'object' && Array.isArray(card.weight.conditions)) {
    effectiveWeight = card.weight.base ?? 1.0;
    for (const cond of card.weight.conditions) {
      const fn = EXTRACTORS[cond.extractor];
      if (fn) {
        try { if ((fn(save) ?? 0) >= (cond.threshold ?? 0)) effectiveWeight = cond.weight ?? effectiveWeight; } catch {}
      }
    }
  } else {
    effectiveWeight = card.weight ?? 1.0;
  }

  // Pass save so compound_and/compound_or tiers can re-evaluate their conditions
  const tierResult = evaluateTiers(value, card.tiers, save);

  return {
    id: card.id,
    label: card.label,
    icon: card.icon,
    weight: effectiveWeight,
    unit: card.unit ?? '',
    extractor: card.extractor,
    value,
    error,
    ...tierResult,
    // #59: Card visibility condition
    visible: card.visibleIf ? _checkVisibility(card.visibleIf, save) : true,
    // Weighted score: 0 = below tier 1, 1 = at tier 1, …, N = at tier N (max), interpolated
    weightedScore: tierResult.tierIndex + 1 + tierResult.pct,
    maxScore: card.tiers.length,
    // Display config pass-through
    pinned: !!card.pinned,
    hideIfMaxed: !!card.hideIfMaxed,
    progressStyle: card.progressStyle || 'bar',
    displayFormat: card.displayFormat || 'number',
    showBenchmark: card.showBenchmark !== false,
  };
}

// #59: Visibility condition checker
function _checkVisibility(visibleIf, save) {
  if (!visibleIf || !visibleIf.extractor) return true;
  const fn = EXTRACTORS[visibleIf.extractor];
  if (!fn) return true;
  try {
    const val = fn(save, visibleIf.param) ?? 0;
    return val >= (visibleIf.threshold || 1);
  } catch { return true; }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Category rating: weighted average of card scores as % of max
// ─────────────────────────────────────────────────────────────────────────────

function rateCategory(evalCards) {
  let weightedSum = 0, weightTotal = 0, maxSum = 0;
  for (const c of evalCards) {
    if (c.cardType === 'info') continue; // info cards do not affect score
    // #43: Error cards have weight=0, so they're excluded from scoring
    const w = c.weight ?? 1.0;
    if (w === 0) continue;
    weightedSum += c.weightedScore * w;
    maxSum      += c.maxScore * w;
    weightTotal += w;
  }
  const pct = maxSum > 0 ? weightedSum / maxSum : 0;
  return { pct: Math.round(pct * 1000) / 1000, weightedSum, maxSum };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Main evaluator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Evaluate all worlds/categories/cards for a given save object.
 * Returns detailed per-card results plus aggregated ratings.
 */
export function evaluateGuidance(save, opts = {}) {
  const t0 = performance.now();
  const cfg = loadConfig();
  const profile = opts.profile ? [] : null;

  // #63: Clear LRU cache at start of each evaluation (new save data)
  _extractorLRU.clear();

  const worldResults = [];

  for (const world of cfg.worlds) {
    const categoryResults = [];

    for (const category of world.categories) {
      const cardResults = [];

      for (const card of category.cards) {
        cardResults.push(evaluateCard(card, save, profile));
      }

      const { pct } = rateCategory(cardResults);

      const scorableCards = cardResults.filter(c => c.cardType !== 'info');
      categoryResults.push({
        id: category.id,
        label: category.label,
        icon: category.icon,
        weight: category.weight ?? 1.0,
        pct,
        cards: cardResults,
        cardsAtMax: scorableCards.filter(c => c.atMax).length,
        cardsTotal: scorableCards.length,
      });
    }

    // World rating = weighted avg of category pcts
    let wSum = 0, wTotal = 0;
    for (const cat of categoryResults) {
      const w = cat.weight ?? 1.0;
      wSum   += cat.pct * w;
      wTotal += w;
    }
    const worldPct = wTotal > 0 ? wSum / wTotal : 0;

    worldResults.push({
      id: world.id,
      label: world.label,
      icon: world.icon,
      weight: world.weight ?? 1.0,
      pct: Math.round(worldPct * 1000) / 1000,
      categories: categoryResults,
    });
  }

  // Global rating = weighted avg of world pcts
  let gSum = 0, gTotal = 0;
  for (const w of worldResults) {
    const wt = w.weight ?? 1.0;
    gSum   += w.pct * wt;
    gTotal += wt;
  }
  const globalPct = gTotal > 0 ? gSum / gTotal : 0;

  // Top recommendations: cards not at max, sorted by how close they are to next tier
  const recommendations = [];
  for (const world of worldResults) {
    for (const cat of world.categories) {
      for (const card of cat.cards) {
        if (card.cardType === 'info') continue;
        if (card.visible === false) continue;
        if (!card.atMax && card.nextThreshold !== null) {
          const gap = card.nextThreshold - card.value;
          recommendations.push({
            worldId: world.id,
            worldLabel: world.label,
            categoryId: cat.id,
            categoryLabel: cat.label,
            categoryIcon: cat.icon,
            card,
            gap,
            pctToNext: card.pct,
            pinned: !!card.pinned,
          });
        }
      }
    }
  }

  // Pinned cards float to the top, then sort by closest to next tier
  recommendations.sort((a, b) => {
    if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
    return b.pctToNext - a.pctToNext;
  });

  const totalMs = Math.round((performance.now() - t0) * 100) / 100;

  // #40/#55 Store last profile for diagnostics
  if (profile) {
    profile.sort((a, b) => b.ms - a.ms);
    _setLastEvalProfile({ ts: Date.now(), totalMs, extractors: profile });
  }

  // #61 Audit log entry
  _appendAuditLog({ globalPct: Math.round(globalPct * 1000) / 1000, totalMs, cardCount: recommendations.length });

  const result = {
    globalPct: Math.round(globalPct * 1000) / 1000,
    worlds: worldResults,
    recommendations: recommendations.slice(0, 20),
    evaluatedAt: Date.now(),
    _evalMs: totalMs,
  };
  if (profile) result._profile = { ts: Date.now(), totalMs, extractors: profile };
  return result;
}

// #61 Evaluation audit log — keeps last 100 evaluations in memory
const _auditLog = [];
function _appendAuditLog(entry) {
  _auditLog.push({ ts: Date.now(), ...entry });
  if (_auditLog.length > 100) _auditLog.shift();
}
export function getAuditLog() { return _auditLog; }

// ─────────────────────────────────────────────────────────────────────────────
//  #52: Batch evaluation — evaluate multiple saves at once
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Evaluate an array of saves concurrently and return an array of results.
 * Each entry in the input array may be an object { save, uid?, opts? }.
 */
export function evaluateGuidanceBatch(items) {
  if (!Array.isArray(items)) throw new TypeError('items must be an array');
  return items.map(item => {
    const save = item?.save ?? item;
    const opts = item?.opts ?? {};
    const uid  = item?.uid ?? null;
    try {
      const result = evaluateGuidance(save, opts);
      return { uid, ok: true, result };
    } catch (e) {
      return { uid, ok: false, error: e.message };
    }
  });
}

export { evaluateTiers, evaluateCard, rateCategory };
