// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

import { loadConfig } from './config.js';
import { EXTRACTORS } from './extractors.js';
import { _extractorLRU, _setLastEvalProfile } from './profile.js';
import { loadCustomExtractors, evaluateCustomExtractor } from './custom-extractors.js';
import { getParamLabel } from './param-options.js';

// ─────────────────────────────────────────────────────────────────────────────
//  #A1: Extractor return contract v2
//  Extractors MAY return either a scalar number OR an object:
//    { value, label?, cost?, source?, subItems?: [{label, value, note?}], note? }
//  _unwrapExtractorResult normalises to { value, meta } where meta carries
//  the optional display-enrichment fields. Scalar returns → { value, meta:{} }.
// ─────────────────────────────────────────────────────────────────────────────
function _unwrapExtractorResult(raw) {
  if (raw == null) return { value: 0, meta: {} };
  if (typeof raw === 'number') return { value: raw, meta: {} };
  if (typeof raw === 'object' && 'value' in raw) {
    const { value, ...rest } = raw;
    const num = typeof value === 'number' && isFinite(value) ? value : (Number(value) || 0);
    // Only keep known enrichment fields (don't leak arbitrary data)
    const meta = {};
    if (rest.label != null) meta.label = String(rest.label);
    if (rest.cost != null) meta.cost = rest.cost;
    if (rest.source != null) meta.source = String(rest.source);
    if (rest.note != null) meta.note = String(rest.note);
    if (Array.isArray(rest.subItems)) meta.subItems = rest.subItems.slice(0, 10);
    return { value: num, meta };
  }
  // Unexpected shape → coerce
  return { value: Number(raw) || 0, meta: {} };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Tier evaluation
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Given a value and an ascending tiers array, determines the current tier.
 *
 * Tier objects support an optional `type` field (defaults to "gte"):
 *   "gte"         — value >= threshold  (default, backward-compatible)
 *   "unlocked"    — value >= 1  (bool display: ✓/✗)
 *   "count_of_n"  — value >= threshold, displays as "X / total"
 *   "pct"         — value 0–100 treated as %, displays as "X%"
 *   "has_item"    — value is 0|1 from parameterised extractor, bool display
 *   "max_any"     — value >= threshold, displays as "Best: X"
 *   "avg"         — value >= threshold, displays as "avg X"
 *   "per_char"    — value >= threshold (count of qualifying chars)
 *   "compound_and"— all conditions[] must individually pass; ignores `value`
 *   "rate"        — value >= threshold, displays with `per` ("hour"/"day")
 *   "lte"         — value <= threshold  (lower is better, e.g. death count)
 *   "between"     — value in [threshold, max]  (range check)
 *   "eq"          — value === threshold  (exact match)
 *   "not"         — value < threshold    (negation / absence check)
 *   "multi_param" — multiple params each with own threshold; all must pass
 *
 * Extra tier fields used by specific types:
 *   total     — (count_of_n) denominator shown in display
 *   per       — (rate) unit string, e.g. "hour" or "day"
 *   conditions— (compound_and) [{extractor, threshold}, ...]
 *   params    — (multi_param) [{param, threshold}, ...]
 *
 * @param {number}  value  — extracted value (ignored for compound_and)
 * @param {Array}   tiers  — ascending tier config array
 * @param {object}  save   — full save object; only needed for compound_and tiers
 * @param {string}  [extractorId] — extractor ID; needed for multi_param tiers
 */
// #44: Cache tier threshold sequences (keyed on tiers array reference)
const _tierThresholdCache = new WeakMap();
function _getTierThresholds(tiers) {
  if (_tierThresholdCache.has(tiers)) return _tierThresholdCache.get(tiers);
  const thresholds = tiers.map(t => t.threshold ?? 0);
  _tierThresholdCache.set(tiers, thresholds);
  return thresholds;
}

function evaluateTiers(value, tiers, save = null, extractorId = null) {
  if (!Array.isArray(tiers) || tiers.length === 0) {
    return { tierIndex: -1, tierLabel: 'No tiers', currentThreshold: 0, nextTier: null, nextThreshold: null, pct: 0, value, displayType: 'gte', total: null, per: null };
  }

  let tierIndex = -1;
  for (let i = 0; i < tiers.length; i++) {
    const tier = tiers[i];
    const type = tier.type || 'gte';
    let passes = false;

    if (type === 'multi_param') {
      // Each entry in tier.params has { param, threshold }. Call the card's extractor
      // with each param — ALL must meet their individual threshold.
      // Skip entries with null/empty param (unconfigured) — treat as not met.
      if (save && extractorId && Array.isArray(tier.params) && tier.params.length > 0) {
        const fn = EXTRACTORS[extractorId];
        if (fn) {
          passes = tier.params.every(p => {
            if (p.param == null || p.param === '') return false; // unconfigured param = not met
            try { return (fn(save, p.param) ?? 0) >= (p.threshold ?? 0); }
            catch { return false; }
          });
        }
      }
    } else if (type === 'compound_and') {
      if (save && Array.isArray(tier.conditions) && tier.conditions.length > 0) {
        passes = tier.conditions.every(cond => {
          const fn = EXTRACTORS[cond.extractor];
          if (!fn) return false;
          try { return (fn(save) ?? 0) >= cond.threshold; }
          catch { return false; }
        });
      }
    } else if (type === 'compound_or') {
      // #42: OR logic — any condition met = tier passes
      if (save && Array.isArray(tier.conditions) && tier.conditions.length > 0) {
        passes = tier.conditions.some(cond => {
          const fn = EXTRACTORS[cond.extractor];
          if (!fn) return false;
          try { return (fn(save) ?? 0) >= cond.threshold; }
          catch { return false; }
        });
      }
    } else if (type === 'lte') {
      // Value must be <= threshold (lower is better, e.g. death count, idle time)
      passes = value <= tier.threshold;
    } else if (type === 'between') {
      // Value must be in [threshold, max] range
      passes = value >= tier.threshold && value <= (tier.max ?? Infinity);
    } else if (type === 'eq') {
      // Exact match
      passes = value === tier.threshold;
    } else if (type === 'not') {
      // Negation: passes when value does NOT meet threshold
      passes = value < tier.threshold;
    } else {
      passes = value >= tier.threshold;
    }

    // #60: Tier skip logic — if a higher tier passes, skip lower ones
    if (passes) tierIndex = i;
    else if (type !== 'compound_and' && type !== 'compound_or' && type !== 'multi_param') break;
    // For compound/multi_param types, continue checking higher tiers (non-sequential)
  }

  const currentTier   = tierIndex >= 0 ? tiers[tierIndex] : null;
  const nextTier      = tierIndex < tiers.length - 1 ? tiers[tierIndex + 1] : null;
  const nextThreshold = nextTier ? nextTier.threshold : null;

  // Display type is taken from the current tier (or next tier if none reached yet)
  const displayType   = (currentTier || nextTier || tiers[0])?.type || 'gte';

  let pct = 0;
  if (nextThreshold !== null) {
    const base  = currentTier ? currentTier.threshold : 0;
    const range = nextThreshold - base;
    // For non-numeric types, pct progress isn't meaningful — set to 0
    if (displayType === 'compound_and' || displayType === 'compound_or') {
      // Calculate compound progress as fraction of conditions met
      const compoundTier = nextTier || currentTier;
      if (save && compoundTier && Array.isArray(compoundTier.conditions) && compoundTier.conditions.length > 0) {
        let met = 0;
        for (const cond of compoundTier.conditions) {
          const fn = EXTRACTORS[cond.extractor];
          if (fn) { try { if ((fn(save) ?? 0) >= cond.threshold) met++; } catch {} }
        }
        pct = met / compoundTier.conditions.length;
      } else {
        pct = 0;
      }
    } else if (displayType === 'multi_param') {
      // Progress = fraction of params that meet their threshold
      const mpTier = nextTier || currentTier;
      if (save && extractorId && mpTier && Array.isArray(mpTier.params) && mpTier.params.length > 0) {
        const fn = EXTRACTORS[extractorId];
        if (fn) {
          let met = 0;
          for (const p of mpTier.params) {
            if (p.param == null || p.param === '') continue; // skip unconfigured params
            try { if ((fn(save, p.param) ?? 0) >= (p.threshold ?? 0)) met++; } catch {}
          }
          const validParams = mpTier.params.filter(p => p.param != null && p.param !== '');
          pct = validParams.length > 0 ? met / validParams.length : 0;
        }
      } else {
        pct = 0;
      }
    } else if (displayType === 'lte') {
      // Inverted progress: lower value = more progress
      pct = range > 0 ? Math.max(0, Math.min(1, (nextThreshold - value) / range)) : 1;
    } else {
      // #56: Smart interpolation — clamp to [0,1] for smooth progress bars
      pct = range > 0 ? Math.max(0, Math.min(1, (value - base) / range)) : 1;
    }
  } else {
    pct = 1; // Already at max tier
  }
  // #44: Use cached thresholds for any threshold-related lookups
  _getTierThresholds(tiers); // warm cache

  // Build rich upcoming tier payload so UI can display param/source names
  // (especially for multi_param tiers like Exalt source requirements).
  const _extractorFn = (save && extractorId) ? EXTRACTORS[extractorId] : null;
  const upcomingTiers = tiers.slice(tierIndex + 1).map(function(t) {
    const row = {
      label: t.label,
      threshold: t.threshold,
      note: t.note || null,
      type: t.type || 'gte',
      total: t.total || null,
      per: t.per || null,
      param: t.param ?? null,
      paramLabel: null,
      params: null,
    };

    if (row.param != null) {
      row.paramLabel = getParamLabel(extractorId, row.param) || null;
    }

    if (row.type === 'multi_param' && Array.isArray(t.params)) {
      row.params = t.params.map(function(p) {
        const pParam = p?.param;
        const pThreshold = p?.threshold ?? 0;
        let pCurrent = 0;
        if (_extractorFn && pParam != null && pParam !== '') {
          try { pCurrent = Number(_extractorFn(save, pParam) ?? 0) || 0; } catch { pCurrent = 0; }
        }
        return {
          param: pParam,
          paramLabel: getParamLabel(extractorId, pParam) || null,
          threshold: pThreshold,
          current: pCurrent,
          met: pCurrent >= pThreshold,
        };
      });
    }

    return row;
  });

  return {
    tierIndex,
    tierLabel: currentTier ? currentTier.label : 'None',
    currentThreshold: currentTier ? (currentTier.threshold ?? 0) : 0,
    nextTier: nextTier ? nextTier.label : null,
    nextThreshold,
    nextNote: nextTier ? (nextTier.note || null) : null,
    pct: Math.round(pct * 1000) / 1000,
    atMax: nextTier === null,
    value,
    displayType,
    // Type-specific display hints
    total: currentTier?.total ?? null,
    per: currentTier?.per ?? null,
    // All upcoming tiers (for sub-card display in review UI)
    upcomingTiers,
  };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Card evaluation
// ─────────────────────────────────────────────────────────────────────────────

function evaluateCard(card, save, profile = null) {
  // Info cards are static text — no extraction or scoring needed
  if (card.cardType === 'info') {
    return {
      id: card.id,
      label: card.label,
      icon: card.icon,
      cardType: 'info',
      text: card.text || '',
      weight: 0,
      unit: '',
      extractor: null,
      value: 0,
      error: null,
      tierIndex: -1,
      tierLabel: null,
      currentThreshold: 0,
      nextTier: null,
      nextThreshold: null,
      pct: 0,
      atMax: true,
      displayType: 'info',
      total: null,
      per: null,
      upcomingTiers: [],
      weightedScore: 0,
      maxScore: 0,
      // Display config pass-through
      pinned: !!card.pinned,
      hideIfMaxed: !!card.hideIfMaxed,
      progressStyle: card.progressStyle || 'bar',
      displayFormat: card.displayFormat || 'number',
      showBenchmark: card.showBenchmark !== false,
    };
  }

  // Alert cards — evaluate each alert condition, return triggered alerts
  if (card.cardType === 'alert') {
    const alerts = Array.isArray(card.alerts) ? card.alerts : [];
    const triggered = [];
    for (const alert of alerts) {
      const fn = EXTRACTORS[alert.extractor];
      if (!fn) continue;
      try {
        const val = fn(save, alert.param ?? null) ?? 0;
        const op = alert.op || 'lt';
        const thr = alert.threshold ?? 0;
        let hit = false;
        if (op === 'lt') hit = val < thr;
        else if (op === 'lte') hit = val <= thr;
        else if (op === 'gt') hit = val > thr;
        else if (op === 'gte') hit = val >= thr;
        else if (op === 'eq') hit = val === thr;
        else if (op === 'neq') hit = val !== thr;
        if (hit) {
          triggered.push({
            label: alert.label || alert.extractor,
            icon: alert.icon || '⚠️',
            severity: alert.severity || 'warning',
            message: alert.message || '',
            extractor: alert.extractor,
            value: val,
            threshold: thr,
            op,
          });
        }
      } catch { /* skip broken alerts */ }
    }
    return {
      id: card.id,
      label: card.label,
      icon: card.icon || '🔔',
      cardType: 'alert',
      weight: 0,
      unit: '',
      extractor: null,
      value: 0,
      error: null,
      tierIndex: -1,
      tierLabel: null,
      currentThreshold: 0,
      nextTier: null,
      nextThreshold: null,
      pct: 0,
      atMax: true,
      displayType: 'alert',
      total: null,
      per: null,
      upcomingTiers: [],
      weightedScore: 0,
      maxScore: 0,
      alerts: triggered,
      alertCount: triggered.length,
      pinned: !!card.pinned,
      hideIfMaxed: false,
      progressStyle: 'bar',
      displayFormat: 'number',
      showBenchmark: false,
    };
  }

  const extractor = EXTRACTORS[card.extractor];
  let value = 0;
  let extractedMeta = {}; // #A1: enrichment data from extractor (label/cost/source/subItems)
  let error = null;
  const t0 = profile ? performance.now() : 0;

  // Resolve effective param once so we can reuse it for paramLabel lookup below
  const paramTier = card.tiers?.find(t => t.param != null);
  const cardParam = card.param ?? paramTier?.param ?? null;

  if (!extractor) {
    // Fall back to custom extractors
    const customDefs = loadCustomExtractors();
    const customDef = customDefs.find(d => d.id === card.extractor);
    if (customDef) {
      try {
        const raw = evaluateCustomExtractor(customDef, save, cardParam);
        const unwrapped = _unwrapExtractorResult(raw);
        value = unwrapped.value;
        extractedMeta = unwrapped.meta;
      } catch (e) { error = e.message; }
    } else {
      error = `Unknown extractor: ${card.extractor}`;
    }
  } else {
    // #63: Check LRU cache first (caches the full result including meta)
    const cacheKey = card.extractor + (cardParam != null ? ':' + cardParam : '');
    const cached = _extractorLRU.get(cacheKey);
    if (cached !== undefined && typeof cached === 'object' && cached !== null && 'value' in cached) {
      value = cached.value;
      extractedMeta = cached.meta || {};
    } else if (cached !== undefined) {
      // Legacy scalar cache entry — still valid
      value = cached;
    } else {
      try {
        const raw = cardParam != null ? extractor(save, cardParam) : extractor(save);
        const unwrapped = _unwrapExtractorResult(raw);
        value = unwrapped.value;
        extractedMeta = unwrapped.meta;
        // #62: avg_per_char mode — divide by character count
        if (card.mode === 'avg_per_char') {
          const chars = save?.CharacterCount ?? save?.playerCount ?? 1;
          value = chars > 0 ? value / chars : value;
        }
        _extractorLRU.set(cacheKey, { value, meta: extractedMeta });
      } catch (e) { error = e.message; }
    }
  }

  // #A2: paramLabel resolution — if extractor didn't supply a label and the
  // card has a numeric/string param that maps to a known name table, use it.
  if (!extractedMeta.label && cardParam != null && cardParam !== '') {
    const resolved = getParamLabel(card.extractor, cardParam);
    if (resolved) extractedMeta.paramLabel = resolved;
  }

  // #40: Record extractor timing
  if (profile) {
    const elapsed = performance.now() - t0;
    profile.push({ extractor: card.extractor, ms: Math.round(elapsed * 100) / 100 });
  }

  // #43: Exclude error cards from scoring — set weight to 0 on error
  // #48: Conditional weights — weight can be { base, conditions: [{ extractor, threshold, weight }] }
  let effectiveWeight;
  if (error) {
    effectiveWeight = 0;
  } else if (card.weight && typeof card.weight === 'object' && Array.isArray(card.weight.conditions)) {
    effectiveWeight = card.weight.base ?? 1.0;
    for (const cond of card.weight.conditions) {
      const fn = EXTRACTORS[cond.extractor];
      if (fn) {
        try { if ((fn(save) ?? 0) >= (cond.threshold ?? 0)) effectiveWeight = cond.weight ?? effectiveWeight; } catch {}
      }
    }
  } else {
    effectiveWeight = card.weight ?? 1.0;
  }

  // Pass save so compound_and/compound_or/multi_param tiers can re-evaluate
  const tierResult = evaluateTiers(value, card.tiers, save, card.extractor);

  return {
    id: card.id,
    label: card.label,
    icon: card.icon,
    weight: effectiveWeight,
    unit: card.unit ?? '',
    extractor: card.extractor,
    param: cardParam,
    value,
    error,
    ...tierResult,
    // #A1/#A2: enrichment from extractor return contract v2 + param name table
    extractedLabel: extractedMeta.label || null,
    paramLabel: extractedMeta.paramLabel || null,
    extractedCost: extractedMeta.cost ?? null,
    extractedSource: extractedMeta.source || null,
    extractedNote: extractedMeta.note || null,
    subItems: extractedMeta.subItems || null,
    // #59: Card visibility condition
    visible: card.visibleIf ? _checkVisibility(card.visibleIf, save) : true,
    // Weighted score: 0 = below tier 1, 1 = at tier 1, …, N = at tier N (max), interpolated
    weightedScore: tierResult.tierIndex + 1 + tierResult.pct,
    maxScore: card.tiers.length,
    // Display config pass-through
    pinned: !!card.pinned,
    hideIfMaxed: !!card.hideIfMaxed,
    showProgressBar: card.showProgressBar !== false,
    progressStyle: card.progressStyle || 'bar',
    displayFormat: card.displayFormat || 'number',
    showBenchmark: card.showBenchmark !== false,
    showSubItems: card.showSubItems !== false,
    showCost: card.showCost !== false,
    showSource: card.showSource !== false,
    tierNoteTemplate: card.tierNoteTemplate || null,
  };
}

// #59: Visibility condition checker
function _checkVisibility(visibleIf, save) {
  if (!visibleIf || !visibleIf.extractor) return true;
  const fn = EXTRACTORS[visibleIf.extractor];
  if (!fn) return true;
  try {
    const val = fn(save, visibleIf.param) ?? 0;
    return val >= (visibleIf.threshold || 1);
  } catch { return true; }
}

// ─────────────────────────────────────────────────────────────────────────────
//  Category rating: weighted average of card scores as % of max
// ─────────────────────────────────────────────────────────────────────────────

function rateCategory(evalCards) {
  let weightedSum = 0, weightTotal = 0, maxSum = 0;
  for (const c of evalCards) {
    if (c.cardType === 'info' || c.cardType === 'alert') continue; // info/alert cards do not affect score
    // #43: Error cards have weight=0, so they're excluded from scoring
    const w = c.weight ?? 1.0;
    if (w === 0) continue;
    weightedSum += c.weightedScore * w;
    maxSum      += c.maxScore * w;
    weightTotal += w;
  }
  const pct = maxSum > 0 ? weightedSum / maxSum : 0;
  return { pct: Math.round(pct * 1000) / 1000, weightedSum, maxSum };
}

// ─────────────────────────────────────────────────────────────────────────────
//  Main evaluator
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Evaluate all worlds/categories/cards for a given save object.
 * Returns detailed per-card results plus aggregated ratings.
 */
export function evaluateGuidance(save, opts = {}) {
  const t0 = performance.now();
  const cfg = loadConfig();
  const profile = opts.profile ? [] : null;

  // #63: Clear LRU cache at start of each evaluation (new save data)
  _extractorLRU.clear();

  const worldResults = [];

  for (const world of cfg.worlds) {
    const categoryResults = [];

    for (const category of world.categories) {
      const cardResults = [];

      for (const card of category.cards) {
        cardResults.push(evaluateCard(card, save, profile));
      }

      const { pct } = rateCategory(cardResults);

      const scorableCards = cardResults.filter(c => c.cardType !== 'info' && c.cardType !== 'alert');
      categoryResults.push({
        id: category.id,
        label: category.label,
        icon: category.icon,
        weight: category.weight ?? 1.0,
        pct,
        cards: cardResults,
        cardsAtMax: scorableCards.filter(c => c.atMax).length,
        cardsTotal: scorableCards.length,
      });
    }

    // World rating = weighted avg of category pcts
    let wSum = 0, wTotal = 0;
    for (const cat of categoryResults) {
      const w = cat.weight ?? 1.0;
      wSum   += cat.pct * w;
      wTotal += w;
    }
    const worldPct = wTotal > 0 ? wSum / wTotal : 0;

    worldResults.push({
      id: world.id,
      label: world.label,
      icon: world.icon,
      weight: world.weight ?? 1.0,
      pct: Math.round(worldPct * 1000) / 1000,
      categories: categoryResults,
    });
  }

  // Global rating = weighted avg of world pcts
  let gSum = 0, gTotal = 0;
  for (const w of worldResults) {
    const wt = w.weight ?? 1.0;
    gSum   += w.pct * wt;
    gTotal += wt;
  }
  const globalPct = gTotal > 0 ? gSum / gTotal : 0;

  // Top recommendations: cards not at max, sorted by how close they are to next tier
  const recommendations = [];
  const allAlerts = [];
  for (const world of worldResults) {
    for (const cat of world.categories) {
      for (const card of cat.cards) {
        if (card.cardType === 'info' || card.cardType === 'alert') continue;
        if (card.visible === false) continue;
        if (!card.atMax && card.nextThreshold !== null) {
          const gap = card.nextThreshold - card.value;
          recommendations.push({
            worldId: world.id,
            worldLabel: world.label,
            categoryId: cat.id,
            categoryLabel: cat.label,
            categoryIcon: cat.icon,
            card,
            gap,
            pctToNext: card.pct,
            pinned: !!card.pinned,
          });
        }
      }
      // Collect triggered alerts from alert cards in this category
      for (const card of cat.cards) {
        if (card.cardType !== 'alert' || !card.alerts || card.alerts.length === 0) continue;
        for (const a of card.alerts) {
          allAlerts.push({
            worldId: world.id,
            worldLabel: world.label,
            categoryId: cat.id,
            categoryLabel: cat.label,
            categoryIcon: cat.icon,
            cardId: card.id,
            cardLabel: card.label,
            ...a,
          });
        }
      }
    }
  }

  // Pinned cards float to the top, then sort by closest to next tier
  recommendations.sort((a, b) => {
    if (a.pinned !== b.pinned) return a.pinned ? -1 : 1;
    return b.pctToNext - a.pctToNext;
  });

  // Per-category recommendation cap (C1) — configurable via cfg.ui.recsPerCategory
  // Default: 3 per category, global cap 20 (same as before). Pinned items always
  // pass through (they've been promoted to the top already).
  const perCatCap = Math.max(0, Number(cfg?.ui?.recsPerCategory ?? 3));
  const globalCap = Math.max(1, Number(cfg?.ui?.recsGlobal ?? 20));
  let cappedRecs = recommendations;
  if (perCatCap > 0) {
    const perCatCount = new Map();
    cappedRecs = recommendations.filter(r => {
      if (r.pinned) return true; // pinned always pass
      const key = r.worldId + '::' + r.categoryId;
      const c = perCatCount.get(key) || 0;
      if (c >= perCatCap) return false;
      perCatCount.set(key, c + 1);
      return true;
    });
  }

  const totalMs = Math.round((performance.now() - t0) * 100) / 100;

  // #40/#55 Store last profile for diagnostics
  if (profile) {
    profile.sort((a, b) => b.ms - a.ms);
    _setLastEvalProfile({ ts: Date.now(), totalMs, extractors: profile });
  }

  // #61 Audit log entry
  _appendAuditLog({ globalPct: Math.round(globalPct * 1000) / 1000, totalMs, cardCount: recommendations.length });

  const result = {
    globalPct: Math.round(globalPct * 1000) / 1000,
    worlds: worldResults,
    recommendations: cappedRecs.slice(0, globalCap),
    alerts: allAlerts,
    evaluatedAt: Date.now(),
    _evalMs: totalMs,
  };
  if (profile) result._profile = { ts: Date.now(), totalMs, extractors: profile };
  return result;
}

// #61 Evaluation audit log — keeps last 100 evaluations in memory
const _auditLog = [];
function _appendAuditLog(entry) {
  _auditLog.push({ ts: Date.now(), ...entry });
  if (_auditLog.length > 100) _auditLog.shift();
}
export function getAuditLog() { return _auditLog; }

// ─────────────────────────────────────────────────────────────────────────────
//  #52: Batch evaluation — evaluate multiple saves at once
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Evaluate an array of saves concurrently and return an array of results.
 * Each entry in the input array may be an object { save, uid?, opts? }.
 */
export function evaluateGuidanceBatch(items) {
  if (!Array.isArray(items)) throw new TypeError('items must be an array');
  return items.map(item => {
    const save = item?.save ?? item;
    const opts = item?.opts ?? {};
    const uid  = item?.uid ?? null;
    try {
      const result = evaluateGuidance(save, opts);
      return { uid, ok: true, result };
    } catch (e) {
      return { uid, ok: false, error: e.message };
    }
  });
}

export { evaluateTiers, evaluateCard, rateCategory };
