// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

// Barrel module — re-exports the full public guidance engine API.
// Consumers should import from './guidance/index.js' (or the back-compat
// shim at modules/guidance-engine.js which forwards here).

export { loadConfig, saveConfig, getConfig } from './config.js';
export { getLastEvalProfile } from './profile.js';
export { convertUnit } from './units.js';
export { EXTRACTORS, EXTRACTOR_IDS, computeRateOfChange } from './extractors.js';
export { EXTRACTOR_META } from './extractor-meta.js';
export { getParamOptions } from './param-options.js';
export { evaluateGuidance, evaluateGuidanceBatch, getAuditLog } from './evaluate.js';
export {
  loadCustomExtractors,
  saveCustomExtractors,
  getCustomExtractorMeta,
  evaluateCustomExtractor,
  getCustomExtractorParamOptions,
  getAllExtractorIDs,
  getAllExtractorMeta,
  getExtractorMeta,
  roundPct,
} from './custom-extractors.js';
