// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

// ─────────────────────────────────────────────────────────────────────────────
//  Name tables for param options (mirrors idleon-review.js constants)
// ─────────────────────────────────────────────────────────────────────────────

const _STATUE_NAMES = ['Power','Mining','Feasty','Health','Speed','Kachow','Lumberbob','Thicc Skin','Oceanman','Ol Reliable','Exp Book','Anvil','Cauldron','Beholder','Bullseye','Twoshoter','Acorn','Beholder2','Snakeskin','Cog','Battleaxe','Eyepatch','Multikill','Triceratops','Key','Cobra','Alchemy','Dragon','Lobster','Seesaw','Golem','Pants'];
const _PO_BOX_NAMES = ['Civil War Memory Box','Locally Sourced Organs','Magician Starterpack','Box of Unwanted Stats','Dwarven Supplies','Blacksmith Box','Taped Up Timber','Carepack From Mum','Sealed Fishheads','Potion Package','Bug Hunting Supplies','Non Predatory Loot Box','Deaths Storage Unit','Utilitarian Capsule','Lazzzy Lootcrate','Science Spare Parts','Trapping Lockbox','Construction Container','Crate of the Creator','Chefs Essentials','Myriad Crate',"Scurvy C'arr'ate",'Box of Gosh','Gaming Lootcrate'];
const _VIAL_NAMES = ['Copper Corona','Sippy Splinters','Mushroom Soup','Spool Sprite','Barium Mixture','Dieter Drink','Skinny 0 Cal','Thumb Pow','Jungle Juice','Barley Brew','Anearful','Tea With Pea','Gold Guzzle','Ramificoction','Seawater','Tail Time','Fly In My Drink','Mimicraught','Blue Flav','Slug Slurp','Pickle Jar','Fur Refresher','Sippy Soul','Crab Juice','Void Vial','Red Malt','Ew Gross Gross','The Spanish Sahara','Poison Tincture','Etruscan Lager','Chonker Chug','Bubonic Burp','Visible Ink','Orange Malt','Snow Slurry','Slowergy Drink','Sippy Cup','Bunny Brew','40-40 Purity','Shaved Ice','Goosey Glug','Ball Pickle Jar','Capachino','Donut Drink','Long Island Tea','Spook Pint','Calcium Carbonate','Bloat Draft','Choco Milkshake','Pearl Seltzer','Krakenade','Electrolyte','Ash Agua','Maple Syrup','Hampter Drippy','Dreadnog','Dusted Drink','Oj Jooce','Oozie Ooblek','Venison Malt','Marble Mocha','Willow Sippy','Shinyfin Stew','Dreamy Drink','Ricecakorade','Ladybug Serum','Flavorgil','Greenleaf Tea','Firefly Grog','Dabar Special','Refreshment','Gibbed Drink','Ded Sap','Royale Cola','Turtle Tisane','Chapter Chug','Sippy Seaweed','Wriggle Water','Rocky Boba','Octosoda','Paper Pint','Scale On Ice','Trash Drank','Crabomayse'];
const _MEAL_NAMES = ['Turkey a la Thank','Egg','Salad','Pie','Frenk Fries','Spaghetti','Corn','Garlic Bread','Garlicless Bread','Pizza','Apple','Pancakes','Corndog','Cabbage','Potato Pea Pastry','Dango','Sourish Fish','Octoplop','Croissant','Canopy','Cannoli','Cheese','Sawdust','Eggplant','Cheesy Bread','Wild Boar','Donut','Riceball','Cauliflower','Durian Fruit','Orange','Bunt Cake','Chocolate Truffle','Leek','Fortune Cookie','Pretzel','Sea Urchin','Mashed Potato','Mutton','Wedding Cake','Eel','Whipped Cocoa','Onion','Soda','Sushi Roll','Buncha Banana','Pumpkin','Cotton Candy','Massive Fig','Head Chef Geustloaf','Kiwi Fruit','Popped Corn','Double Cherry','Ratatouey','Giant Tomato','Wrath Grapes','Sausy Sausage','Seasoned Marrow','Sticky Bun','Frazzleberry','Misterloin Steak','Large Pohayoh','Bill Jack Pepper','Burned Marshmallow','Yumi Peachring','Plumpcakes','Nyanborgir','Tempura Shrimp','Woahtermelon','Cookies','Singing Seed','Tasty Treat','Giga Chip','2nd Wedding Cake'];
const _CHIP_NAMES = ['Grounded Nanochip','Grounded Motherboard','Grounded Software','Grounded Processor','Potato Chip','Conductive Nanochip','Conductive Motherboard','Conductive Software','Conductive Processor','Chocolatey Chip','Galvanic Nanochip','Galvanic Motherboard','Galvanic Software','Galvanic Processor','Wood Chip','Silkrode Nanochip','Silkrode Motherboard','Silkrode Software','Silkrode Processor','Poker Chip','Omega Nanochip','Omega Motherboard'];
const _ARTIFACT_NAMES = ['Moai Head','Maneki Kat','Ruble Cuble','Fauxory Tusk','Gold Relic','Genie Lamp','Silver Ankh','Emerald Relic','Fun Hippoete','Arrowhead','10 AD Tablet','Ashen Urn','Amberite','Triagulon','Billcye Tri','Frost Relic','Chilled Yarn','Causticolumn','Jade Rock','Dreamcatcher','Gummy Orb','Fury Relic','Cloud Urn','Weatherbook','Giants Eye','Crystal Steak','Trilobite Rock','Opera Mask','Socrates','The True Lantern','The Onyx Lantern','The Shim Lantern','The Winz Lantern','Deathskull','Obsidian','Pointagon','Ender Pearl','Fang of the Gods','Nomenclature','Me First Dollar','Enigma Fragment'];
const _ARTIFACT_CODENAMES = ['Moai','Maneki_kat','Ruble_Cuble','Fauxory_Tusk','Gold_Relic','Genie_Lamp','Silver_Ankh','Emerald_Relic','Fun_Hippoete','Arrowhead','10_AD_Tablet','Ashen_Urn','Amberite','Triagulon','Billcye_Tri','Frost_Relic','Chilled_Yarn','Causticolumn','Jade_Rock','Dreamcatcher','Gummy_Orb','Fury_Relic','Cloud_Urn','Weatherbook','Giants_Eye','Crystal_Steak','Trilobite_Rock','Opera_Mask','Socrates','True_Lantern','Onyx_Lantern','Shim_Lantern','Winz_Lantern','Deathskull','Obsidian','Pointagon','Ender_Pearl','Fang_of_Gods','Nomenclature','First_Dollar','Enigma_Fragment'];
const _STAMP_NAMES = {
  combat: ['Sword Stamp','Heart Stamp','Mana Stamp','Tomahawk Stamp','Target Stamp','Shield Stamp','Longsword Stamp','Kapow Stamp','Fist Stamp','Battleaxe Stamp','Agile Stamp','Vitality Stamp','Book Stamp','Manamoar Stamp','Clover Stamp','Scimitar Stamp','Bullseye Stamp','Feather Stamp','Polearm Stamp','Violence Stamp','Buckler Stamp','Hermes Stamp','Sukka Foo','Arcane Stamp','Avast Yar Stamp','Steve Sword','Blover Stamp','Stat Graph Stamp','Gilded Axe Stamp','Diamond Axe Stamp','Tripleshot Stamp','Blackheart Stamp','Maxo Slappo Stamp','Sashe Sidestamp','Intellectostampo','Conjocharmo Stamp','Dementia Sword Stamp','Golden Sixes Stamp','Stat Wallstreet Stamp','Void Sword Stamp','Void Axe Stamp','Captalist Stats Stamp','Splosion Stamp','Gud EXP Stamp'],
  skills: ['Pickaxe Stamp','Hatchet Stamp','Anvil Zoomer Stamp','Lil Mining Baggy Stamp','Twin Ores Stamp','Choppin Bag Stamp','Duplogs Stamp','Matty Bag Stamp','Smart Dirt Stamp','Cool Diggy Tool Stamp','High IQ Lumber Stamp','Swag Swingy Tool Stamp','Alch Go Brrr Stamp','Brainstew Stamps','Drippy Drop Stamp','Droplots Stamp','Fishing Rod Stamp','Fishhead Stamp','Catch Net Stamp','Fly Intel Stamp','Bag o Heads Stamp','Holy Mackerel Stamp','Bugsack Stamp','Buzz Buzz Stamp','Hidey Box Stamp','Purp Froge Stamp','Spikemouth Stamp','Shiny Crab Stamp','Gear Stamp','Stample Stamp','Saw Stamp','Amplestample Stamp','SpoOoky Stamp','Flowin Stamp','Prayday Stamp','Banked Pts Stamp','Cooked Meal Stamp','Spice Stamp','Ladle Stamp','Nest Eggs Stamp','Egg Stamp','Lab Tube Stamp','Sailboat Stamp','Gamejoy Stamp','Divine Stamp','Multitool Stamp','Skelefish Stamp','Crop Evo Stamp','Sneaky Peeky Stamp','Jade Mint Stamp','Summoner Stone Stamp','White Essence Stamp','Triad Essence Stamp','Dark Triad Essence Stamp','Amber Stamp','Little Rock Stamp','Hardhat Stamp'],
  misc: ['Questin Stamp','Mason Jar Stamp','Crystallin','Arcade Ball Stamp','Gold Ball Stamp','Potion Stamp','Golden Apple Stamp','Ball Timer Stamp','Card Stamp','Forge Stamp','Vendor Stamp','Sigil Stamp','Talent I Stamp','Talent II Stamp','Talent III Stamp','Talent IV Stamp','Talent V Stamp','Talent S Stamp','Multikill Stamp','Biblio Stamp','DNA Stamp','Refinery Stamp','Atomic Stamp','Cavern Resource Stamp','Study Hall Stamp','Kruker Stamp','Corale Stamp'],
};

// ─────────────────────────────────────────────────────────────────────────────
//  getParamOptions — returns organized picker options for a given extractor
//  Returns Array<{ value: string, label: string, group: string, desc?: string }>
// ─────────────────────────────────────────────────────────────────────────────

export function getParamOptions(extId) {
  const _SKILL_NAMES = ['Combat','Mining','Smithing','Chopping','Fishing','Alchemy','Catching','Trapping','Construction','Worship','Cooking','Breeding','Laboratory','Sailing','Divinity','Gaming','Farming','Sneaking','Summoning','Spelunking'];
  const _CLASS_NAMES = {0:'Beginner',2:'Journeyman',3:'Maestro',4:'Voidwalker',5:'Infinilyte',7:'Warrior',8:'Barbarian',9:'Squire',10:'Blood Berserker',12:'Divine Knight',14:'Death Bringer',16:'Royal Guardian',19:'Archer',20:'Bowman',21:'Hunter',22:'Siege Breaker',25:'Beast Master',29:'Wind Walker',31:'Mage',32:'Wizard',33:'Shaman',34:'Elemental Sorcerer',35:'Spiritual Monk',36:'Bubonic Conjuror',40:'Arcane Cultist'};

  switch (extId) {
    case 'stamps.hasStamp':
      return [
        ..._STAMP_NAMES.combat.map((n, i) => ({ value: `0:${i}`, label: n, group: 'Combat Stamps' })),
        ..._STAMP_NAMES.skills.map((n, i) => ({ value: `1:${i}`, label: n, group: 'Skills Stamps' })),
        ..._STAMP_NAMES.misc.map((n,  i) => ({ value: `2:${i}`, label: n, group: 'Misc Stamps' })),
      ];

    case 'stamps.tabAvg':
    case 'stamps.tabMaxed':
      return [
        { value: '0', label: 'Combat Stamps', group: 'Stamp Tabs' },
        { value: '1', label: 'Skills Stamps', group: 'Stamp Tabs' },
        { value: '2', label: 'Misc Stamps',   group: 'Stamp Tabs' },
      ];

    case 'statues.statueLevel':
    case 'statues.statueGold':
      return _STATUE_NAMES.map((n, i) => ({ value: String(i), label: n, group: 'Statues' }));

    case 'postOffice.boxLevel':
      return _PO_BOX_NAMES.map((n, i) => ({ value: String(i), label: n, group: 'Post Office Boxes' }));

    case 'vials.level':
    case 'vials.isMaxed':
      return _VIAL_NAMES.map((n, i) => ({ value: String(i), label: n, group: 'Vials' }));

    case 'meals.hasMeal':
      return _MEAL_NAMES.map((n, i) => ({ value: String(i), label: n, group: 'Meals' }));

    case 'chips.hasChip':
      return _CHIP_NAMES.map(n => ({ value: n, label: n, group: 'Lab Chips' }));

    case 'artifacts.hasArtifact':
      return _ARTIFACT_CODENAMES.map((cod, i) => ({ value: cod, label: _ARTIFACT_NAMES[i] || cod, group: 'Artifacts' }));

    case 'achievements.hasAchievement':
      return Array.from({ length: 300 }, (_, i) => ({ value: String(i), label: `Achievement #${i}`, group: 'Achievements' }));

    case 'skills.avgLevel':
    case 'skills.maxLevel':
    case 'skills.totalAcrossChars':
      return _SKILL_NAMES.map((n, i) => ({ value: String(i), label: n, group: 'Skills' }));

    case 'characters.classUnlocked':
      return Object.entries(_CLASS_NAMES).map(([id, name]) => ({ value: id, label: name, group: 'Classes' }));

    case 'characters.afkInWorld':
      return Array.from({ length: 8 }, (_, i) => ({ value: `w${i + 1}`, label: `World ${i + 1}`, group: 'Worlds' }));

    case 'alchemy.cauldronBubbles':
    case 'alchemy.cauldronAvgLevel':
      return [
        { value: '0', label: 'Power Cauldron (Orange)',  group: 'Cauldrons' },
        { value: '1', label: 'Quicc Cauldron (Green)',   group: 'Cauldrons' },
        { value: '2', label: 'High-IQ Cauldron (Purple)',group: 'Cauldrons' },
        { value: '3', label: 'Kazam Cauldron (Yellow)',  group: 'Cauldrons' },
      ];

    case 'deathnote.worldSkulls':
      return Array.from({ length: 7 }, (_, i) => ({ value: String(i + 1), label: `World ${i + 1}`, group: 'Worlds' }));

    case 'atoms.atomLevel':
      return Array.from({ length: 20 }, (_, i) => ({ value: String(i), label: `Atom #${i}`, group: 'Atoms' }));

    case 'cooking.mealsAbove':
      return [5, 10, 15, 20, 25, 30].map(l => ({ value: String(l), label: `Level ${l}+`, group: 'Level Thresholds' }));

    case 'gemShop.perCharPurchases':
      return Array.from({ length: 12 }, (_, i) => ({ value: String(i), label: `Character ${i + 1}`, group: 'Characters' }));

    case 'characters.withStarSign':
      return [];

    case 'bribes.setBought':
    case 'bribes.setProgress':
      return Array.from({ length: 9 }, (_, i) => ({ value: String(i), label: `Bribe Set ${i + 1}`, group: 'Bribe Sets' }));

    case 'account.dustByType':
      return [
        { value: '0', label: 'Dust Type 1', group: 'Dust Types' },
        { value: '1', label: 'Dust Type 2', group: 'Dust Types' },
        { value: '2', label: 'Dust Type 3', group: 'Dust Types' },
        { value: '3', label: 'Dust Type 4', group: 'Dust Types' },
        { value: '4', label: 'Dust Type 5', group: 'Dust Types' },
      ];

    case 'account.bonesByType':
      return [
        { value: '0', label: 'Bones Type 1', group: 'Bone Types' },
        { value: '1', label: 'Bones Type 2', group: 'Bone Types' },
        { value: '2', label: 'Bones Type 3', group: 'Bone Types' },
        { value: '3', label: 'Bones Type 4', group: 'Bone Types' },
      ];

    case 'account.tachyonByType':
      return [
        { value: '0', label: 'Tachyon Type 1', group: 'Tachyon Types' },
        { value: '1', label: 'Tachyon Type 2', group: 'Tachyon Types' },
        { value: '2', label: 'Tachyon Type 3', group: 'Tachyon Types' },
        { value: '3', label: 'Tachyon Type 4', group: 'Tachyon Types' },
        { value: '4', label: 'Tachyon Type 5', group: 'Tachyon Types' },
        { value: '5', label: 'Tachyon Type 6', group: 'Tachyon Types' },
      ];

    case 'stamps.exaltBonusPct':
      return [
        { value: 'all',       label: 'All Sources (total)',        group: 'Exalt Sources' },
        { value: 'base',      label: 'Base 100%',                  group: 'Exalt Sources' },
        { value: 'atom',      label: 'Aluminium Atom Lv',          group: 'Exalt Sources' },
        { value: 'emperor',   label: 'Emperor Armor Set (+20)',     group: 'Exalt Sources' },
        { value: 'spelunk',   label: 'Spelunking Exalt Fragments',  group: 'Exalt Sources' },
        { value: 'event',     label: 'Event Shop Bonus (+20)',      group: 'Exalt Sources' },
        { value: 'gemShop',   label: 'Gem Shop Exalt Purchases',    group: 'Exalt Sources' },
        { value: 'compass',   label: 'Compass Exalt Slots',         group: 'Exalt Sources' },
        { value: 'palette',   label: 'Palette Bonus',               group: 'Exalt Sources' },
        { value: 'exotic',    label: 'Exotic Bonus',                group: 'Exalt Sources' },
        { value: 'charm',     label: 'Ninja Charm Bonus',           group: 'Exalt Sources' },
        { value: 'sushi',     label: 'Sushi Station #23 (+5)',      group: 'Exalt Sources' },
        { value: 'sigil',     label: 'Ethereal Sigils Bonus',       group: 'Exalt Sources' },
        { value: 'tesseract', label: 'Tesseract Bonus',             group: 'Exalt Sources' },
      ];

    case 'cards.byTier':
      return [
        { value: '1', label: 'Bronze (≥1 kill)',       group: 'Card Tiers' },
        { value: '2', label: 'Silver (≥3 kills)',      group: 'Card Tiers' },
        { value: '3', label: 'Gold (≥10 kills)',       group: 'Card Tiers' },
        { value: '4', label: 'Platinum (≥50 kills)',   group: 'Card Tiers' },
        { value: '5', label: 'Ruby (≥200 kills)',      group: 'Card Tiers' },
        { value: '6', label: 'Majestic (≥1000 kills)', group: 'Card Tiers' },
      ];

    default:
      return [];
  }
}

// ─────────────────────────────────────────────────────────────────────────────
//  getParamLabel — resolve a param index/code to a human-readable label
//  Used by evaluate.js to enrich card results (so render shows "Void Stamp"
//  instead of "23"). Returns null if no name table is registered for this
//  extractor or the param is out of range.
// ─────────────────────────────────────────────────────────────────────────────

export function getParamLabel(extId, param) {
  if (extId == null || param == null || param === '') return null;
  const opts = getParamOptions(extId);
  if (!opts || opts.length === 0) return null;
  const pStr = String(param);
  // Try exact value match (covers both numeric and codename params)
  const hit = opts.find(o => o.value === pStr);
  if (hit) return hit.label;
  // Numeric fallback: some extractors use composite values like "0:12" (stamps)
  // — caller may pass the raw number, we already matched above if exact.
  return null;
}

