// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

// ─────────────────────────────────────────────────────────────────────────────
//  Performance profiling (#40, #46, #55)
// ─────────────────────────────────────────────────────────────────────────────

let _lastEvalProfile = null;

export function getLastEvalProfile() { return _lastEvalProfile; }

// ─────────────────────────────────────────────────────────────────────────────
//  #63: LRU cache for extractor results (per-evaluation, keyed on extractor+param)
// ─────────────────────────────────────────────────────────────────────────────

class _LRUCache {
  constructor(max = 512) { this._max = max; this._map = new Map(); }
  get(key) {
    if (!this._map.has(key)) return undefined;
    const v = this._map.get(key);
    this._map.delete(key); this._map.set(key, v);
    return v;
  }
  set(key, val) {
    this._map.delete(key);
    this._map.set(key, val);
    if (this._map.size > this._max) this._map.delete(this._map.keys().next().value);
  }
  clear() { this._map.clear(); }
}

// Per-evaluation LRU — shared by evaluateGuidance, cleared between evaluations
let _extractorLRU = new _LRUCache(512);

export { _lastEvalProfile, _setLastEvalProfile, _extractorLRU, _LRUCache };

function _setLastEvalProfile(p) { _lastEvalProfile = p; }
