// Auto-generated by scripts/maintenance/split-guidance-engine.mjs
// Source: modules/guidance-engine.js (pre-refactor). Do not edit the old monolith;
// edit the files in modules/guidance/ instead.

// ─────────────────────────────────────────────────────────────────────────────
//  #58: Measurement unit helpers
// ─────────────────────────────────────────────────────────────────────────────

const _UNIT_MAP = {
  '%': { base: '%', factor: 1 },
  'k': { base: '', factor: 1000 },
  'M': { base: '', factor: 1e6 },
  'hrs': { base: 'min', factor: 60 },
  'min': { base: 'sec', factor: 60 },
  'sec': { base: 'ms', factor: 1000 },
};

export function convertUnit(value, fromUnit, toUnit) {
  const from = _UNIT_MAP[fromUnit], to = _UNIT_MAP[toUnit];
  if (!from || !to || from.base !== to.base) return value;
  return value * from.factor / to.factor;
}

